#!/usr/bin/env ruby
require 'halfling'
require "optparse"
require 'erb'

arg=OptionParser.new do |opts|
  opts.on("--new [AppName]", "create new Halfling app") do |name|
    require "fileutils"
    
    cur_pwd = Dir.pwd
    dirname = name.downcase
    root = File.join(cur_pwd, dirname)
    camelcase = name.split(/[-_]/).map.with_index{|x,i| i > 0 ? x.capitalize : x}.join
    classname = camelcase.capitalize
    
    Dir.mkdir root rescue Errno::EEXIST
    
    Dir.chdir File.join(File.dirname(__FILE__),'../data/app_structure')
    skelly = Dir['**/*']
    
    skelly.each do |f|
      if File.directory?(f)
        FileUtils.mkdir File.join(root, f) rescue Errno::EEXIST
      elsif f.match(/\.tt$/)
        erb = ERB.new(File.read(f))
        File.open(File.join(root, f.chomp(File.extname(f))), 'w') { |file| file.write(erb.result(binding)) }
      else
        FileUtils.cp(f, File.dirname(File.join(root, f)))
      end 
    end
    
    puts "New app #{classname} in #{root}."
  end
end
arg.banner=<<EOS
Halfling stuff
EOS
arg.version=Halfling::VERSION

arg.parse!
